#!/usr/bin/env python
# -*- coding: utf-8 -*-

if __name__ == '__main__':
	from libtigernotes.opts import LogOpts as opts
	p = opts()
    try:
        p.run()
    except Exception as e:
        sys.exit(e)
